image: node:16

definitions:
    caches:
        cypress: $HOME/.cache/Cypress
        #TODO: cache node modules from auth-frontend
    steps:
        - step: &deps
              name: Install npm dependencies
              caches:
                  - node
              script:
                  - npm install
        - step: &checks
              name: Check JS/CSS
              caches:
                  - node
              script:
                  - npm run check
        - step: &build-assets
              name: Build Code
              caches:
                  - node
              script:
                  - export $(cat .env | xargs)
                  - npm run build -- --env=environment=$ENVIRONMENT
              artifacts:
                  - dist/**
        - step: &build-policies
              name: Build B2C
              image: mcr.microsoft.com/powershell
              script:
                  - pwsh -Command "scripts/Build-CustomPolicies.ps1 -FilePath src/policies/custom_policies"
              artifacts:
                  - src/policies/custom_policies/**
        - step: &deploy
              name: Deploy B2C
              script:
                  - export $(cat .env | xargs)
                  - pipe: atlassian/azure-storage-deploy:1.0.2
                    variables:
                        SOURCE: "dist/**"
                        DESTINATION: "https://$STORAGE_ACCOUNT.blob.core.windows.net/$STORAGE_CONTAINER?"
                        DESTINATION_SAS_TOKEN: $AzureStorageSasToken
                        EXTRA_ARGS: "--recursive --overwrite=true"
                        DEBUG: "true"
                  - npx ieftool deploy -t $TENANT_ID -c $CLIENT_ID -s $SECRET -p src/policies/custom_policies/Environments/$ENVIRONMENT
        - step: &e2e-tests
              name: "E2E tests - SSO - Chrome Browser"
              image: cypress/browsers:node16.5.0-chrome97-ff96
              script:
                  - git clone git@bitbucket.org:calmisland/kidsloop-auth-frontend.git --branch dev
                  - cd kidsloop-auth-frontend
                  - npm i --no-audit --no-progress
                  - npm run test:sso:default
                  - npm run e2e:reports
                  - cd ..
              caches:
                  - cypress
              artifacts:
                  # store any generates images and videos as artifacts
                  - kidsloop-auth-frontend/cypress/screenshots/**
                  - kidsloop-auth-frontend/cypress/cucumber-json
                  - kidsloop-auth-frontend/cypress/videos/**
                  - kidsloop-auth-frontend/test-reports/**

pipelines:
    default:
        - step: *deps
        - step: *checks
        - step:
              name: Setup environment - SSO
              script:
                  - echo 'ENVIRONMENT="SSO"' >> .env
              artifacts:
                  - .env
        - parallel:
              - step: *build-assets
              - step: *build-policies

    branches:
        master:
            - step: *deps
            - step: *checks
            - step:
                  name: Setup environment
                  script:
                      - echo 'ENVIRONMENT="SSO"' >> .env
                  artifacts:
                      - .env
            - parallel:
                  - step: *build-assets
                  - step: *build-policies
            - step:
                  <<: *deploy
                  deployment: SSO
            - step:
                  <<: *e2e-tests
            - step:
                  name: Setup environment - Alpha
                  script:
                      - echo 'ENVIRONMENT="Alpha-Dev"' >> .env
                  artifacts:
                      - .env
            - parallel:
                  - step: *build-assets
                  - step: *build-policies
            - step:
                  <<: *deploy
                  deployment: Alpha-Dev
    custom:
        deploy-loadtest:
            - step: *deps
            - step: *checks
            - step:
                  name: Setup environment
                  script:
                      - echo 'ENVIRONMENT="LOADTEST"' >> .env
                  artifacts:
                      - .env
            - parallel:
                  - step: *build-assets
                  - step: *build-policies
            - step:
                  <<: *deploy
                  deployment: LOADTEST
        deploy-alpha-dev:
            - step: *deps
            - step: *checks
            - step:
                  name: Setup environment
                  script:
                      - echo 'ENVIRONMENT="Alpha-Dev"' >> .env
                  artifacts:
                      - .env
            - parallel:
                  - step: *build-assets
                  - step: *build-policies
            - step:
                  <<: *deploy
                  deployment: Alpha-Dev
        deploy-staging:
            - step: *deps
            - step: *checks
            - step:
                  name: Setup environment
                  script:
                      - echo 'ENVIRONMENT="Staging"' >> .env
                  artifacts:
                      - .env
            - parallel:
                  - step: *build-assets
                  - step: *build-policies
            - step:
                  <<: *deploy
                  deployment: Staging
        deploy-VN-Beta:
            - step: *deps
            - step: *checks
            - step:
                  name: Setup environment
                  script:
                      - echo 'ENVIRONMENT="VN-Beta"' >> .env
                  artifacts:
                      - .env
            - parallel:
                  - step: *build-assets
                  - step: *build-policies
            - step:
                  <<: *deploy
                  deployment: VN-Beta
        deploy-ID-Beta:
            - step: *deps
            - step: *checks
            - step:
                  name: Setup environment
                  script:
                      - echo 'ENVIRONMENT="ID-Beta"' >> .env
                  artifacts:
                      - .env
            - parallel:
                  - step: *build-assets
                  - step: *build-policies
            - step:
                  <<: *deploy
                  deployment: ID-Beta
