#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16

pipelines:
    default:
        - step:
            name: Lint & Build
            caches:
              - node
            script:
              - npm install
              - npm run lint
              # - npm run check
              - npm run build -- --env=environment=SSO
            artifacts:
              - dist/**
              - scripts/**
              - src/policies/custom_policies/**
        - step:
            name: Deploy build to SSO storage
            script:
              - pipe: atlassian/azure-storage-deploy:1.0.2
                variables:
                  SOURCE: 'dist/**'
                  DESTINATION: 'https://$AccountStorage_SSO.blob.core.windows.net/$AccountStorageContainer_SSO?'
                  DESTINATION_SAS_TOKEN: $AzureStorageSasToken_SSO
                  EXTRA_ARGS: '--recursive --overwrite=true'
                  DEBUG: 'true'
        - step:
            name: Build IEF policies
            image: mcr.microsoft.com/powershell
            script:
              - pwsh -Command "scripts/Build-CustomPolicies.ps1 -FilePath src/policies/custom_policies"
            artifacts:
              - src/policies/custom_policies/**
        - step:
            name: Upload IEF policies to SSO
            script:
              - npx ieftool deploy -t $Tenant_SSO -c $Client_Id_SSO -s $Client_Secret_SSO -p src/policies/custom_policies/Environments/SSO-HM
        
    branches:
        master:
            - step:
                name: Build & lint
                caches:
                    - node
                script:
                    - npm install
                    - npm run lint
                    # - npm run check
                    - npm run build
                artifacts:
                    - dist/**
                    - scripts/**
                    - src/policies/custom_policies/**
            - step:
                name: Build IEF policies
                image: mcr.microsoft.com/powershell
                script:
                    - pwsh -Command "scripts/Build-CustomPolicies.ps1 -FilePath src/policies/custom_policies"
                artifacts:
                    - src/policies/custom_policies/**
            - step:
                name: Upload IEF policies to SSO
                script:
                    - echo "tenant_SSO" $Tenant_SSO
                    - npx ieftool deploy -t $Tenant_SSO -c $Client_Id_SSO -s $Client_Secret_SSO -p src/policies/custom_policies/Environments/SSO-MH
