#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16

pipelines:
  default:
    - step:
        name: Build
        caches:
          - node
        script:
          - npm install
          - npm run build
        artifacts:
          - dist/**
    - step:
        name: Code linting
        script:
          - npx eslint .
        caches:
          - node
  deploy:
    sso:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm install
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Code linting
          script:
            - npx eslint .
          caches:
            - node
      - step:
          name: Build IEF
          script:
            - 
      - step:
          name: Upload Html templates to B2C storage
          script:
            - npm install
            - npm run build
            - pipe: atlassian/azure-storage-deploy:1.0.2
              variables:
                SOURCE: 'dist/*'
                DESTINATION: 'https://$AccountName.blob.core.windows.net/$ContainerName?'
                DESTINATION_SAS_TOKEN: $AzureStorageSasToken
                EXTRA_ARGS: '--recursive --overwrite=true'
          artifacts:
            - dist/*
      

