image: node:16

definitions:
    steps:
        - step: &deps
              name: Install npm dependencies
              caches:
                  - node
              script:
                  - npm install
        - step: &checks
              name: Check JS/CSS
              caches:
                  - node
              script:
                  - npm run check
        - step: &build-assets
              name: Build HTML/JS/CSS/images
              caches:
                  - node
              script:
                  - export $(cat .env | xargs)
                  - npm run build -- --env=environment=$ENVIRONMENT
              artifacts:
                  - dist/**
        - step: &build-policies
              name: Build B2C policy XML
              image: mcr.microsoft.com/powershell
              script:
                  - pwsh -Command "scripts/Build-CustomPolicies.ps1 -FilePath src/policies/custom_policies"
              artifacts:
                  - src/policies/custom_policies/**
        - step: &deploy
              name: Deploy assets/policies to B2C
              script:
                  - export $(cat .env | xargs)
                  - pipe: atlassian/azure-storage-deploy:1.0.2
                    variables:
                        SOURCE: "dist/**"
                        DESTINATION: "https://$STORAGE_ACCOUNT.blob.core.windows.net/$STORAGE_CONTAINER?"
                        DESTINATION_SAS_TOKEN: $AzureStorageSasToken
                        EXTRA_ARGS: "--recursive --overwrite=true"
                        DEBUG: "true"
                  - npx ieftool deploy -t $TENANT_ID -c $CLIENT_ID -s $SECRET -p src/policies/custom_policies/Environments/$ENVIRONMENT
        - step: &e2e-tests
              name: Cypress Regression for IAM
              script:
                  - pipe: atlassian/trigger-pipeline:4.3.1
                    variables:
                        BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                        BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                        REPOSITORY: "kidsloop-auth-frontend"
                        ACCOUNT: "calmisland"
                        CUSTOM_PIPELINE_NAME: "cypress-tests-SSO-chrome"
                        BRANCH_NAME: "dev"

pipelines:
    default:
        - step:
            name: clone azure frontend repo
            script:
                - git clone git@bitbucket.org:calmisland/kidsloop-auth-frontend.git 
        - step: *deps
        - step: *checks
        - step:
              name: Setup environment
              script:
                  - echo 'ENVIRONMENT="SSO"' >> .env
              artifacts:
                  - .env
        - parallel:
              - step: *build-assets
              - step: *build-policies

    branches:
        master:
            - step: *deps
            - step: *checks
            - step:
                  name: Setup environment
                  script:
                      - echo 'ENVIRONMENT="SSO"' >> .env
                  artifacts:
                      - .env
            - parallel:
                  - step: *build-assets
                  - step: *build-policies
            - step:
                  <<: *deploy
                  deployment: SSO
            - step: *e2e-tests
    custom:
        deploy-loadtest:
            - step: *deps
            - step: *checks
            - step:
                  name: Setup environment
                  script:
                      - echo 'ENVIRONMENT="LOADTEST"' >> .env
                  artifacts:
                      - .env
            - parallel:
                  - step: *build-assets
                  - step: *build-policies
            - step:
                  <<: *deploy
                  deployment: LOADTEST
        deploy-alpha-dev:
            - step: *deps
            - step: *checks
            - step:
                  name: Setup environment
                  script:
                      - echo 'ENVIRONMENT="Alpha-Dev"' >> .env
                  artifacts:
                      - .env
            - parallel:
                  - step: *build-assets
                  - step: *build-policies
            - step:
                  <<: *deploy
                  deployment: Alpha-Dev
