#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16

pipelines:
    default:
        - step:
            name: Build & lint
            caches:
              - node
            script:
              - npm install
              - npm run lint
              # - npm run check
              - npm run build
            artifacts:
              - dist/**
              - scripts/**
              - src/policies/custom_policies/**
        - step:
            name: Build IEF policies
            image: mcr.microsoft.com/powershell
            script:
              - pwsh -Command "scripts/Build-CustomPolicies.ps1 -FilePath src/policies/custom_policies"
            artifacts:
              - src/policies/custom_policies/**
        - step:
            name: Upload IEF policies to SSO
            script:
              - npx ieftool deploy -t $Tenant_SSO -c $Client_Id_SSO -s $Client_Secret_SSO -p src/policies/custom_policies/Environments/SSO-MH
    branches:
        master:
            - step:
                name: Build & lint
                caches:
                    - node
                script:
                    - npm install
                    - npm run lint
                    # - npm run check
                    - npm run build
                artifacts:
                    - dist/**
                    - scripts/**
                    - src/policies/custom_policies/**
            - step:
                name: Build IEF policies
                image: mcr.microsoft.com/powershell
                script:
                    - pwsh -Command "scripts/Build-CustomPolicies.ps1 -FilePath src/policies/custom_policies"
                artifacts:
                    - src/policies/custom_policies/**
            - step:
                name: Upload IEF policies to SSO
                script:
                    - npx ieftool deploy -t $Tenant_SSO -c $Client_Id_SSO -s $Client_Secret_SSO -p src/policies/custom_policies/Environments/SSO-MH
            # - step:
            #     name: Deploy To B2c Storage
            #     - pipe: atlassian/azure-storage-deploy:1.0.2
            #       variables:
            #         SOURCE: 'dist/**'
            #         DESTINATION: 'https://$AccountName.blob.core.windows.net/$ContainerName?'
            #         DESTINATION_SAS_TOKEN: $AzureStorageSasToken
            #         EXTRA_ARGS: '--recursive --overwrite=true'
            #     artifacts:
            #       - dist/*
            # trigger: manual  # Uncomment to make this a manual deployment.
