name: Deploy all environments

on:
    workflow_dispatch:

jobs:
    generate-matrix:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Generate matrix
              id: generate-matrix
              run: |
                  ENVIRONMENTS=$(./scripts/fetch-github-environments.sh ${{ secrets.GITHUB_TOKEN}})

                  echo $ENVIRONMENTS

                  echo "::set-output name=environments::$ENVIRONMENTS"

        outputs:
            environments: ${{ steps.generate-matrix.outputs.environments }}

    deploy:
        runs-on: ubuntu-latest

        needs: generate-matrix

        strategy:
            fail-fast: false
            matrix:
                environment: ${{ fromJson(needs.generate-matrix.outputs.environments) }}

        environment:
            name: ${{ matrix.environment }}
        env:
            ENVIRONMENT_NAME: ${{ matrix.environment }}

        # Duplicate of cd `deploy-alpha` job, as unfortunately reusable workflows don't support `strategy`
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: npm

            - name: Install dependencies
              run: npm i

            - name: Lint HTML/JS/CSS
              run: npm run check

            - name: Build B2C policies
              shell: pwsh
              run: ./scripts/Build-CustomPolicies.ps1 -FilePath ./src/policies

            - name: Build assets
              run: npm run build -- --env=environment=${{ env.ENVIRONMENT_NAME }}

            - name: Read appsettings.json into environment
              run: |
                  ./scripts/convert-policy-settings-json-to-env-format.sh ${{ env.ENVIRONMENT_NAME }} >> $GITHUB_ENV

            - name: Check environment
              run: |
                  echo ${{ env.AZURE_STORAGE_ACCOUNT }}
                  echo ${{ env.AZURE_STORAGE_CONTAINER }}

            - name: Upload assets to B2C storage
              uses: azure/CLI@v1
              with:
                  azcliversion: 2.33.1
                  inlineScript: az storage blob upload-batch --account-name '${{ env.AZURE_STORAGE_ACCOUNT }}' -d '${{ env.AZURE_STORAGE_CONTAINER }}' --sas-token '${{ secrets.B2C_STORAGE_ACCOUNT_SAS }}' --source 'dist'

            - name: Upload B2C policies
              uses: azure-ad-b2c/deploy-trustframework-policy@v5.3
              with:
                  folder: "src/policies/Environments/${{ env.ENVIRONMENT_NAME }}"
                  files: "TRUST_FRAMEWORK_BASE.xml,TRUST_FRAMEWORK_EXTENSIONS.xml,TRUST_FRAMEWORK_TENANT_CONFIG.xml,TRUST_FRAMEWORK_LOCALIZATION.xml,RELYING_PARTY_SIGN_UP_LOG_IN.xml"
                  tenant: ${{ env.TENANT_ID }}
                  clientId: ${{ env.DEPLOYMENT_APP_CLIENT_ID }}
                  clientSecret: ${{  secrets.B2C_DEPLOY_CLIENT_SECRET }}
                  verbose: true
